src/views/pages/Login.vue
Hooking to the form submit event allows us to utilize browser built in behaviors like submitting a form when pressing enter. This commit fixes issue #2
=> Add form submit handling to login view

package.json, src/shared/api.js, vue.config.js
* Proxy API requests to the backend when using devServer.
* When developing, use relative paths for API requests. In production use absolute URIs for API requests.
* Add npm start script which starts the devServer
=> Fix CORS issues with devServer

src/App.vue, src/views/pages/Login.vue, src/views/portfolio/projects/Projects.vue
This PR adds functionality for checking the stored JWT token status during app init. Token status is checked by calling `v1/user/self` API to fetch user details. On a successful API response we set axios and jQuery authorization headers and proceed with routing etc. If an error occurs, we clear the session storage token and redirect to the login page.
Also changes successful login attempts to set the axios and jQuery authorization headers.
Fixes #8
=> Check authorization status on application initialization

src/i18n/locales/en.json
Because there is no visible feedback to the entered regex and you can't be sure if it works until you upload a bom I thought a bit of explanation was in order.
For me it was not clear that the regex needs to match the whole string. (`Pattern.matches()`)
Rendering of the change:
=> add a bit of explanation to the internal component dialog

src/views/portfolio/projects/ProjectList.vue
The link injected for project/uuid cannot be intercepted by vue-router, which causes a full page reload on click. Adding a custom event and using $router.push instead ensures the routing is done by vue-router and improve page transition.
**Suggestion :** Also, you might consider using the table component from bootsrap-vue instead bootstrap-table because it has better integration with Vue.js (custom slot definition) and will reduce your amount of dependencies for the frontend.
=> Prevent page reload on opening page project

docker/Dockerfile, docker/docker-compose.yml, docker/docker-entrypoint.sh, public/static/config.json, src/main.js, src/shared/oidc.json, src/views/pages/Login.vue
Some providers require OIDC clients to request more than the default scopes. Auth0 for example has extra scopes for `groups`, `roles` and `permissions`: https://auth0.com/docs/extensions/authorization-extension/use-rules-with-the-authorization-extension
=> Make oidc scopes configurable

public/static/oidc-callback.html, src/App.vue, src/containers/DefaultHeaderProfileDropdown.vue, src/router/index.js, src/shared/utils.js, src/views/components/ProfileEditModal.vue, src/views/pages/Login.vue, src/views/pages/Page404.vue, src/views/pages/PasswordForceChange.vue, src/views/portfolio/projects/ProjectList.vue
- stores the location before the user is redirected to the login page in the query param "redirect". after successful login, the user gets redirected to this url if it is set. navigation flow will be as follows:
1. http://localhost:8081/projects/285384c9-a18f-465f-921b-d465efd9c43e
2. http://localhost:8081/login?redirect=%2Fprojects%2F285384c9-a18f-465f-921b-d465efd9c43e
3. http://localhost:8081/projects/285384c9-a18f-465f-921b-d465efd9c43e
- uses global navigation guard to ensure the jwt is valid and redirects to login if it is not.
previous implementation checked the jwt only when the app was created. if it was expired afterwards, the app did not recognized that. the guard will take care of this now.
- some other small fixes:
- "go back" on 404-page always directed the user to "/" --> …
=> redirect to original location upon successful login

src/containers/DefaultHeaderProfileDropdown.vue, src/views/pages/Login.vue
* Don't show *Update Profile* and *Change Password* options in profile dropdown when authentication was performed with LDAP or OIDC. Until now, the frontend suggested that these actions were possible, when in fact they arent
* Don't try to check OIDC availability in the API server when OIDC wasn't configured in the frontend. This mainly resolves some confusion some folks had, where they'd see OIDC related error-toasts without having it configured
=> Minor UX improvements

src/views/administration/accessmanagement/OidcUsers.vue
E-Mail is not persisted for `OidcUser`s and is only available in each user's session. See https://github.com/stevespringett/Alpine/blob/alpine-parent-1.9.0/alpine/src/main/java/alpine/model/OidcUser.java#L53. This column will be empty 100% of the time, which may cause confusion.
=> Remove email from OidcUsers columns

docker/Dockerfile
Hi, I am running Dependency Track 4.2.1 on OpenShift. OpenShift applies its Restricted SCC to deployments by default, whereby it assigns an arbitrary UID to the container and also assigns it GID=0. Therefore if we update Dockerfiles to chown/chgrp GID=0 and also chmod g=u (so that the group 0 has same permissions as user) we can ensure the Dockerfiles are compatible with OpenShift best practice.
Reference: "Support arbitrary user ids" https://docs.openshift.com/container-platform/4.1/openshift_images/create-images.html
=> Update Dockerfile for OpenShift

docker/docker-compose.yml, docker/docker-entrypoint.sh, public/static/config.json, src/main.js, src/shared/oidc.json, src/views/pages/Login.vue
This PR fixes issue #79. Now it is possible to set env variable `OIDC_LOGIN_BUTTON_TEXT` and it's value will be shown as OIDC login button text.
=> Fix #79 and add option for OIDC login button text

src/shared/common.js, src/views/portfolio/projects/ComponentVulnerabilities.vue, src/views/portfolio/projects/ProjectFindings.vue, src/views/portfolio/projects/ProjectPolicyViolations.vue
Resolves https://github.com/DependencyTrack/dependency-track/issues/946 
As this is my first issue for DependencyTrack, please let me know if I need to make any changes or you would like to see anything done differently. 
- Adds makeAnalysisStateLabelFormatter to common utilities to translate analysis states to human readable names.
- Updates 3 components to use the analysis state label formatter:
- [ComponentVulnerabilities.vue#L77](https://github.com/DependencyTrack/frontend/blob/master/src/views/portfolio/projects/ComponentVulnerabilities.vue#L77)
- [ProjectPolicyViolations.vue#L101](https://github.com/DependencyTrack/frontend/blob/master/src/views/portfolio/projects/ProjectPolicyViolations.vue#L101)
- [ProjectFindings.vue#L125](https://github.com/DependencyTrack/frontend/blob/master/sr …
=> Adds language specific analysis state values in tables

src/views/portfolio/vulnerabilities/Vulnerability.vue
Tweak the URL used in cweLink to use HTTPS instead of HTTP.
Whilst modern browsers do now automatically redirect HTTP to HTTPS, it's better that the secure protocol be used by default so as to "practice what we preach".
=> Update CWE Link to use HTTPS

src/views/dashboard/ChartAuditingProgress.vue, src/views/dashboard/ChartComponentVulnerabilities.vue, src/views/dashboard/ChartPolicyViolations.vue, src/views/dashboard/ChartPortfolioVulnerabilities.vue, src/views/dashboard/ChartProjectVulnerabilities.vue
Should fix #92 or at least make it more usable. It may be a little awkward for users used to the old large hover hitboxes though will avoid the issues as seen in #92.
=> Reduce hit radius of graphs to avoid #92

public/static/oidc-callback.html, src/views/pages/Login.vue
Multiple IdPs disallow usage of custom query parameters in the authorization request's `redirect_uri`. By storing the target URL in `state`, `redirect_uri` can remain static without query params.
Fixes #64, related to https://github.com/DependencyTrack/frontend/pull/47#issuecomment-1024666503
Tested with Auth0 and Keycloak, both for `code` and `implicit` flows. Here's a GIF showing this working with Keycloak:
=> OIDC: Store redirect URL in `state`

README.md, src/i18n/locales/en.json, src/views/portfolio/projects/ProjectCreateProjectModal.vue
Extracted component hardcoded labels in project creation to i18n labels.
Display component list in project creation sorted by name.
Fixed lang files path in README.md.
=> Extracted component hardcoded labels in project creation to i18n labels.

src/views/portfolio/vulnerabilities/Vulnerability.vue
Thanks to @msymons for reporting!
=> Fix "Affected Projects" tab in Vulnerability view not being visible to users with `VIEW_VULNERABILITY` permission

src/views/portfolio/projects/ProjectFindings.vue
The API server only really records anything besides comments and the analysis state *after* the state has been changed. 
It also makes sense that the complementary fields are only set after the analysis state changed, and the frontend should reflect this intended workflow.
https://user-images.githubusercontent.com/5693141/154135189-2c853ced-1627-4147-9872-450e667e6cfe.mp4
=> Disable complementary analysis fields until a state is set

src/views/portfolio/projects/ProjectList.vue, src/views/portfolio/projects/ProjectUploadBomModal.vue
Show classifier in project list to improve overview of heterogeneous projects. 
When monitoring different kind of projects(docker images, libraries etc. ), it is helpful to see the classifier in project list.
=> show classifier in project list

src/views/dashboard/ChartPolicyViolationBreakdown.vue
@stevespringett Do you remember why this was commented out? The code seems to be working just fine:
Fixes #91
=> Show Security Risk in policy violations overview (fixes #91)

.github/workflows/_meta-build.yaml, .github/workflows/ci-build.yaml, .github/workflows/ci-publish.yaml, .github/workflows/ci-release.yaml, docker/Dockerfile.alpine
This PR picks up the idea from the backend CI and aims to fix the incorrect version reported by the releases originated from the current CI.
* splits off publish build to a separate workflow
* address the comment from the previous CI PR https://github.com/DependencyTrack/frontend/pull/141#issuecomment-1130326345
=> refactor: split of publish workflow

src/containers/DefaultHeaderProfileDropdown.vue, src/i18n/locales/en.json, src/mixins/globalVarsMixin.js, src/router/index.js, src/views/components/ProfileEditModal.vue
Addresses https://github.com/DependencyTrack/frontend/issues/167
Signed-off-by: ege-dw <enora.germond@deveryware.com>
=> Display the name of the connected user

src/views/administration/notifications/Alerts.vue
Addresses https://github.com/DependencyTrack/dependency-track/issues/1173
=> Add switch to enable or disable notifications

.github/workflows/ci-publish.yaml, .github/workflows/ci-release.yaml
As done previously for the API server repo in https://github.com/DependencyTrack/dependency-track/commit/c8abaa3401e37ac207e776f79657a95dccdb8ce9
=> Use bot account when creating releases via GitHub Actions

vue.config.js
Configuring the build to not generate source maps in production. Local testing shows it reduces the final Docker image size by 40%.
=> Disable source maps for production builds #192

src/views/administration/configuration/EmailTestConfigurationModal.vue
Hover text for email configuration test input box was copypasta. Added appropriate wording.
Reported in #161.
=> Fixed email configuration tooltip wording

src/i18n/locales/en.json, src/validation/index.js, src/views/administration/AdminMenu.vue, src/views/administration/Administration.vue, src/views/administration/configuration/TaskScheduler.vue
Enhancement request described in [#1542](https://github.com/DependencyTrack/dependency-track/issues/1542).
Backend PR : [1841](https://github.com/DependencyTrack/dependency-track/pull/1841)
Signed-off-by: Alioune SY <sy_alioune@yahoo.fr>
=> Make background tasks periodicity configurable

src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
Fixes an issue where the `VulnerabilityDetailsModal` would not render any information at all, if no CVSS scores were returned by the API.
This surfaced for OSV vulnerabilities that on some occasions don't have CVSS scores, despite having CVSS vectors. This can and will be addressed in the OSV mirror task, but the frontend should be able to handle these situations as well.
Before:
After:
=> Calculate CVSS scores dynamically when only the vector is known

package-lock.json, package.json
Fixes:
* https://security.snyk.io/vuln/SNYK-JS-MERGE-1040469
* https://security.snyk.io/vuln/SNYK-JS-MERGE-1042987
`vue-bootstrap-toggle` only uses a single function of `merge`. That function still exists in v2 of `merge`, so this version bump is not a breaking change. See https://github.com/rhyek/vue-bootstrap-toggle/blob/16cf66e4346119ea5b72ec2abeafe524b55bbaee/src/index.vue#L51
Further, the vulnerabilities (both prototype pollutions) are not exploitable, as neither of the arguments passed to `merge.recursive` are user-controllable.
Still performing the update to make scanners happy.
=> Bump `merge` to 2.1.1

src/views/administration/vuln-sources/VulnSourceOSVAdvisories.vue
**Issue:** OSV toggling was misbehaving, was getting disabled because of handle function.
**Fix:** Update functionality to handle list of ecosystem properly.
Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>
=> Quick-fix : OSV ecosystem toggle handling

src/views/portfolio/projects/ProjectDetailsModal.vue
This will fix a bug that cause the wrong tags to be displayed in the details dialog when switching between projects versions. For more details about the impact, see linked issue. This caused by a conversation routine between DTO and Domain-Model, which was skipped when the DTO was allready initialized. In this case the previously displayed tags were displayed, even if they where not defined in the version of the project.
Fixes #188
=> Fix Project View Details display wrong tags

src/views/portfolio/projects/ComponentDetailsModal.vue
This will fix an error, that caused the License in the Legal tab of the Component details view was not set, even if the component had an resolved license.
The previous routine intialized the selectedLicense at a time, where the component was not always present. In my case the component was only present, after a hot reload during development. So initialized this field when the modal opens. I've tracked this by putting a console.log statement at the end of the `retrieveLicenses` method. In most cases `this.component` was an empty object.
Fixes #223
=> Fix Component View Details not initialize license

src/assets/scss/_custom.scss
This effectively reduce the width of an `expanded-row` by 2 pixels to remove the scrollbar, when it is not necessary. It turns out that `border-collapse: collapse;` on the table causing the scrollbars to be shown. Because of setting this attribute to `seperate` will change the appearance, i adjusted the margin of the expanded-rows instead. The commit will overwrite the `margin-right: -15px`, which is set by the row class.
Tested on Chrome and Firefox. Please someone test it on Safari.
Fixes #248
=> Remove unnecessary hz-scrollbar on expanded rows

.github/workflows/ci-release.yaml
This just makes the destination of version bump commits dependent on the branch the workflow is running on, instead of always pushing to `master`. This will allow us to run the workflow on release branches as well.
=> Enable release creation from non-master branches

.github/workflows/ci-release.yaml
It uses `master` per default, which is not the intention when releasing from a release branch.
=> Specify the target branch when creating a release via GitHub CLI

src/views/administration/accessmanagement/PortfolioAccessControl.vue, src/views/components/ActionableListGroupItem.vue
When managing ACLs, the projects assigned to teams has a non-clickable name.
It thought it might be handy to make them clickable.
I did encode the url for XSS, but I am not sure this is needed when letting Vue take care of rendering the template.
(And it would be hard to embed a XSS payload in a uuid generated by the database)
=> ACL: Make project names clickable

src/i18n/locales/en.json, src/shared/api.json, src/views/portfolio/projects/ProjectAddVersionModal.vue
Adds an includeACL parameter to the project clone api, accompanying https://github.com/DependencyTrack/dependency-track/pull/2122
Signed-off-by: Valentijn Scholten [valentijnscholten@gmail.com](mailto:valentijnscholten@gmail.com)
=> Allow cloning of ACL during Project cloning

src/views/portfolio/projects/ProjectFindings.vue
Handle 404 responses from the `/api/v1/analysis` endpoint.
The endpoint previously returned HTTP 200 with an empty response body in case no analysis was found.
This has changed with https://github.com/DependencyTrack/dependency-track/pull/2196
https://github.com/DependencyTrack/dependency-track/issues/1932
The frontend shows an error toast whenever it encounters a non-successful response status. Using the `validateStatus` [request configuration](https://axios-http.com/docs/req_config), the 404 status code can be treated as acceptable, such that no error toast is shown anymore.
=> Handle 404 responses from `/api/v1/analysis`

src/views/portfolio/projects/ProjectEpss.vue, src/views/portfolio/projects/ProjectFindings.vue
Information about the version status of a component is currently only displayed in the `Components` tab of a project.
Also adding this information to the `Audit Vulnerabilities` and the `Exploit Predictions` tab of a project improves the usability of those two tabs, because it is no longer needed to switch tabs to check for version status information.
Closes #356 
Enhanced the `/finding/project/<projectUUID>` endpoint in the [Backend PR](https://github.com/DependencyTrack/dependency-track/pull/2272) to correctly display the information in the tabs.
=> Display version status in `Audit Vulnerabilities` and `Exploit Predictions` tab

src/i18n/locales/en.json, src/views/portfolio/projects/Project.vue, src/views/portfolio/projects/ProjectDashboard.vue
This PR adds the "Last BOM Import" timestamp to the project overview page.
Closes #147
=> Display last BOM import in project overview

src/i18n/locales/en.json
Missing i18n message for team deletion.
See https://github.com/DependencyTrack/dependency-track/issues/1532
- Backend PR : https://github.com/DependencyTrack/dependency-track/pull/2287
~~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~~
=> Fix : Deleting a team with existing ACL

src/views/portfolio/projects/ProjectDependencyGraph.vue
Improvement to #336.
Focusing on a component in the dependency graph can result in huge amounts of data being sent from the backend to pre-expand a graph, because in big nested graphs the same components can appear multiple times and the current approach of focusing on components includes every duplicate component in its response.
With this PR, the needed components for pre-expanding a graph are being de-duplicated before being sent as a response to the frontend, resulting in a huge reduction of sent data (e.g. ~50MB => ~60KB).
Backend: [#1997](https://github.com/DependencyTrack/dependency-track/issues/1997)
[Backend PR](https://github.com/DependencyTrack/dependency-track/pull/2296)
~- [ ] This PR introduces new or alters existing behavior, and I have updated the …
=> Improve focusing on components in dependency graph

src/views/portfolio/projects/ProjectPolicyViolations.vue
If a project does not have a dependency graph (or rather no direct dependencies), no component information will be shown in the `Policy Violations` tab of a project.
This PR fixes this bug by showing component information in the `Policy Violations` tab regardless of whether the project has a dependency graph or not.
Backend Issue: [#2311](https://github.com/DependencyTrack/frontend/issues/373)
=> Fix component information not showing in policy violations

.github/PULL_REQUEST_TEMPLATE.md
Correct the link to `CONTRIBUTING.md` in the pull request template.
It was previously pointing to a branch of the `dependency-track` repo that doesn't exist anymore.
N/A
N/A
=> Fix link to CONTRIBUTING.md in PR template

src/views/administration/AdminMenu.vue, src/views/administration/configuration/JiraConfig.vue
This PR fixes the position of the Jira configuration in the admin menu.
It also contains the necessary frontend changes for https://github.com/DependencyTrack/dependency-track/pull/2404.
Fixes #371
=> Fix position of Jira configuration in admin menu

src/views/administration/vuln-sources/EcosystemModal.vue
While selecting ecosystems for OSV mirroring, same ecosystem can be selected multiple times. This may cause duplicate downloading of one ecosystem (large files) from OSV client, which may result in repeated processing of already processed vulnerabilities.
Issue: https://github.com/DependencyTrack/dependency-track/issues/2473
Update the endpoint to get only inactive ecosystems, to fix the selection of ecosystems to be unique.
=> Issue-2473 : fix OSV ecosystem to be unique (frontend)

src/views/portfolio/components/ComponentSearch.vue, src/views/portfolio/projects/ProjectList.vue
This PR implements the support for deep-linking to results in the component search, which makes it possible to easily share/re-use search results by copying the current URL for the result.
Two new functionalities are added to the component search for this improvement:
- If the URL contains the criteria for a search query, the query will be inserted into the component search and the search will be performed.
- Clicking on the `Search` button changes the URL in the address bar to reflect the current search criteria for the result.
#425
**Examples:**
- `/components#/search/COORDINATES/group=acme/name=test/version=dev`
- `/components#/search/HASH/123456789987654321`
- `/components#/search/PACKAGE_URL/pkg%3Amaven%2Forg.yaml%2Fsnakeyaml%401.19%3Ftype%3Djar`
=> Deep-Linking support for component search

src/views/policy/PolicyCondition.vue
The policy feature should support the vulnerability ID in a policy so that organisations can create policy related to particular vulnerability ID.
https://github.com/DependencyTrack/dependency-track/issues/2557
=> Issue-2557 : add vulnerability id in policy condition

src/router/index.js, src/views/administration/AdminMenu.vue
Fix: Move jira configuration
PR #393 was missing the update of the deep linking configuration to fix #371
=> Fix: Move jira configuration

src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
For exact versions in affected components, if purl has version already appended, the frontend was appending the version again making it look like test-purl@3.4@3.4
Quick fix to add a check to avoid double version append.
=> Fix duplicate version in affected components tab

src/views/administration/notifications/Alerts.vue
Added new project notification to frontend alert template, to make it selectable.
The new PROJECT_CREATED notification is not visible in the frontend, as the frontend does not pull the list of notifications dynamically.
=> Added new project notification to frontend alert template

src/views/portfolio/projects/ComponentVulnerabilities.vue, src/views/portfolio/projects/ProjectFindings.vue, src/views/portfolio/vulnerabilities/VulnerabilityList.vue
2023-02-15 Attempt 2 at this PR: 
The Audit Vulnerabilities tab for a project has an extra column that can be shown to list the aliases of a vulnerability. This PR improves the alignment of these aliases to make it look a little bit better.
Old:
New:
I have also added this optional column to the global Vulnerabilities and Components lists
- Vulnerabilities with multiple aliases look ugly in Audit Vulnerabilities tab
- Alias column can be useful also in Components list and Vulnerabilities list
Not everybody might feel this is the "perfect" solution, but let's not [make "perfect" the enemy of "good"](https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good) :-)
Not sure if there's a practical way to wrap around each alias without using <br/>
Signed-off-by: Valentijn Scholten …
=> aliases: improve alias column, show aliases optionally in all vulnerability lists 

src/shared/common.js, src/views/portfolio/projects/Project.vue, src/views/portfolio/projects/ProjectCreateProjectModal.vue, src/views/portfolio/projects/ProjectDetailsModal.vue
Completes #168 by also showing the newly added tags on the project list page (#319) in lowercase.
- #168
1. Changed tags from uppercase to lowercase using CSS.
2. The value of a tag in the tag-URL on the project details page was not properly escaped resulting in a possible code injection.
3. The inline style was changed to bootstrap classes in project dialog.
=> show tags in lowercase on the project list page

src/shared/common.js, src/views/portfolio/projects/ComponentVulnerabilities.vue, src/views/portfolio/projects/ProjectFindings.vue, src/views/portfolio/vulnerabilities/Vulnerability.vue, src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue, src/views/portfolio/vulnerabilities/VulnerabilityList.vue
This PR fixes a defect where not all aliases of vulnerabilities would be displayed. See #477 for details.
This PR also prevents the same vulnerability ID being displayed multiple times, and adds sorting of alias IDs so that the output is more visually consistent.
Fixes #477
=> Fix not all vulnerability aliases being displayed

src/views/portfolio/projects/ComponentVulnerabilities.vue
This PR fixes the hyperlinks for aliases on the component vulnerabilities page. 
They previously linked to `/components/vulnerabilities/<SOURCE>/<VULNID>` instead of `/vulnerabilities/<SOURCE>/<VULNID>`.
N/A
N/A
=> Fix aliases hyperlink on component vulnerabilities page

src/shared/common.js, src/views/portfolio/projects/Project.vue, src/views/portfolio/projects/ProjectList.vue
This PR fixes incorrect tag links being generated on the project page.
Instead of using relative URLs, make use of the Vue router to refer to the target route by name.
Fixes #483
=> Fix incorrect project tag links

docker/docker-compose.yml
Fixes a regression in docker-compose file for dtrack-frontend service
The application directory moved from `/app` to `/opt/owasp/dependency-track-frontend`, but `docker-compose.yml` still used the old one in the volume.
https://github.com/DependencyTrack/frontend/commit/d12ddfa9dcc80bb7ac262eaec70c214a77b81a38#diff-6e3cd4368541f4b438a0ce9dfe5b45e3a04426f80b43546092e76f088bd2e8dc
[#493](https://github.com/DependencyTrack/frontend/issues/493)
- [~] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly
=> Fix volume dir regression in docker-compose

src/router/index.js
dashboard was treated as a public route although it's not
fixes regression from f16c314f4e0fde8c04d6b983fbff2f283b96c8b2
Since #502, any route without the `meta.permission` property is treated as a public route. I did not check the dashboard route to see if it met this requirement. As a result, when calling the dashboard, there was no redirection to the login page if you were logged out, which caused consecutive errors on the dashboard page.
=> fix: no defined permission for dashboard

docker/etc/nginx/conf.d/default.conf
When testing over an ipv6-only stack I noticed the frontend would not be reachable, as nginx listens on ipv4 only by default. This change adds the second required directive.
- [/] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly
=> Add dualstack nginx listen

.github/workflows/_meta-build.yaml, .github/workflows/ci-publish.yaml
This PR fixes warnings in our GitHub Actions workflows due to deprecation of the `set-output` command.
N/A
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Fix GHA `set-output` deprecation warnings

src/views/components/ExternalReferencesDropdown.vue, src/views/portfolio/projects/Component.vue, src/views/portfolio/projects/Project.vue
As a comfort function, it would be great to have the external references as well as the description of a project available on the project page header.
* resolves https://github.com/DependencyTrack/frontend/issues/484
* resolves https://github.com/DependencyTrack/frontend/issues/487
On projects and components containing external references the following drop down menu is shown on the right side of the "details" lane:
Opening the drop-down shows the link types with the url as hover tooltip, links are opened in new browser tabs:
Projects/Components without external references keep unchanged:
Project with a tags and long description:
Full description via tooltip:
Description gets inlined when shrinking the page:
and disappears completely on even smaller pages, like the metrics do.
=> Add external references and description to project page

src/shared/api.json, src/views/portfolio/projects/ProjectDependencyGraph.vue
In this PR, I change the way the frontend collect information about children node in the Dependency Graph.
Before, for each child, a request to the backend was made. In this PR, I merge all requests in one on a new endpoint created in this PR: https://github.com/DependencyTrack/dependency-track/pull/2623
fixes https://github.com/DependencyTrack/dependency-track/issues/2255
=> Issue 2255: fetch all node children of dependency graph in one request

.github/workflows/_meta-build.yaml, README.md, package-lock.json, package.json
This PR adds the `--openssl-legacy-provider` Node option to all NPM scripts.
It is a follow-up to #541 which makes the above option necessary until we can upgrade webpack.
N/A
N/A
=> Ensure `--openssl-legacy-provider` is set for all NPM scripts

src/views/portfolio/projects/ProjectFindings.vue
This PR fixes a defect where vulnerability aliases would not be displayed when expanding rows in the *Audit Vulnerabilities* table.
Fixes #556
N/A
=> Fix aliases not being displayed in expanded rows of findings table

src/views/portfolio/projects/ComponentDetailsModal.vue, src/views/portfolio/projects/ProjectAddComponentModal.vue
As a follow-up to #452, this PR fixes the following issues:
* Expressions typed into the *Component Details* dialog were not sent to the API server
* The license expression input field was missing from the *Add Component* dialog
Also, a previously existing issue that prevented selected licenses from being unselectable.
N/A
N/A
=> Fix license expression input fields

src/views/policy/CreatePolicyModal.vue
When new policy is created, it displays message 'Project created' instead of 'Policy created'. Variable being used needs to be updated.
NA
NA
=> Quick fix : policy_created message

src/views/portfolio/projects/ProjectDependencyGraph.vue
Fixes a regression introduced in #455, which caused the "outdated" warning sign to not be displayed in the dependency graph.
N/A
N/A
=> Fix outdated indicator not being displayed in dependency graph

src/i18n/locales/en.json, src/views/pages/Login.vue
Hide default login form when OIDC available. An additional 'More options' link will be shown below the OIDC login button. A click on the link restores the visibility of the default login form elements.
Resolves #429
=> Hide default login form when OIDC available

src/i18n/locales/en.json, src/views/administration/notifications/Alerts.vue
When editing an Alert, the form lost focus after every 750ms. This worsened the user experience because the user had to keep re-selecting the form field to make changes. Instead of auto-saving after every 750ms, the form now has a Submit button and will no longer lose focus unintentionally.
Fixes #421
=> Keep focus when editing Alerts (fixes #421)

docker/docker-entrypoint.d/30-oidc-configuration.sh
Use `touch` instead of `mount` to check whether `config.json` is mounted. In some containerized environments, the `mount` command is not available, which caused the previous check to fail.
Additionally, modify the `config.json` file in place when populating it from environment variables, instead of using a temporary file.
The populated config will be logged by the entrypoint script.
> **Note**  
> Needs to be backported to the `4.9.x` branch.
Fixes #60
Closes #511
Fixes #513
Closes #514
Example output:
```
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-oidc-configuration.sh
30-oidc-configuration.sh: info: effective config: {"API_BASE_URL":null,"API_WITH_CREDENTIALS":null,"OIDC_ISSUER":"foo","OIDC_CLIENT_ID":"bar","OIDC_SCOPE":"openid profile …
```
=> Use `touch` instead of `mount` to check whether `config.json` is mounted

docker/docker-entrypoint.d/30-oidc-configuration.sh
Use `touch` instead of `mount` to check whether `config.json` is mounted. In some containerized environments, the `mount` command is not available, which caused the previous check to fail.
Additionally, modify the `config.json` file in place when populating it from environment variables, instead of using a temporary file.
The populated config will be logged by the entrypoint script.
Fixes #60
Closes #511
Fixes #513
Closes #514
Example output:
```
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-oidc-configuration.sh
30-oidc-configuration.sh: info: effective config: {"API_BASE_URL":null,"API_WITH_CREDENTIALS":null,"OIDC_ISSUER":"foo","OIDC_CLIENT_ID":"bar","OIDC_SCOPE":"openid profile email","OIDC_FLOW":null,"OIDC_LOGIN_BUTTON_TEXT":"baz"}
```
=> Backport: Use `touch` instead of `mount` to check whether `config.json` is mounted

package-lock.json
Backports #633 in order to resolve CVE-2023-46234.
N/A
N/A
=> Backport: bump browserify-sign from 4.2.1 to 4.2.2

src/i18n/locales/en.json, src/views/administration/notifications/Alerts.vue
Adds an alert option to log successful publishing.
https://owasp.slack.com/archives/C6R3R32H4/p1699978082979659
API Server PR: https://github.com/DependencyTrack/dependency-track/pull/3211
=> Add alert option to log successful publishing

src/views/portfolio/projects/Project.vue
Fixes wrong route when not on overview tab in project view
Fixes #641
=> Fix routing bug on version dropdown when not on Overview tab #641

src/views/portfolio/projects/ProjectList.vue, vue.config.js
Include project component count on the projects listing page (hidden by default).
Fixes #630
The other metrics fields have specific code to handle the case where the metrics aren't provided; I don't think that is necessary in this case where just a number is being rendered, not a progress bar. Example with two projects, one with metrics and one without:
(The diff accidentally builds on #682)
=> Include component count in projects list

src/views/portfolio/projects/ProjectList.vue
This PR makes the vulnerabilities and policy violations use unique field IDs in the bootstrap table spec. The docs say:
> This field must be unique, or some unknown problems may occur.
The frontend also uses the field id to save which columns the user has marked as visible or not.
Fixes #608
Tested with vulnerabilities present and absent, and with policy violations absent or zero. I don't have a project handy that has any policy violations, but the behaviour shouldn't change based on >0 vs absent.
=> Use unique fields for project list metrics columns

src/router/index.js, src/views/portfolio/projects/FindingAudit.vue, src/views/portfolio/projects/ProjectFindings.vue, src/views/portfolio/vulnerabilities/AffectedProjects.vue, vue.config.js
This PR fixes a pair of bugs and factors out the finding detail view into its own single file component.
It might be easiest to review commit by commit.
Fixes #688 in 3895307e761d56e259b340edfc6e9a320db98e41
I originally planned to make a new view to show a specific finding, and wanted to re-use the detail view from the audit page. This was inlined in a way that was very hard to re-use (or read!). In my journey to try and re-use it I came across [Steve's earlier investigations](https://github.com/wenzhixin/bootstrap-table/issues/4754), and was eventually able to pull it out into its own component as it looks like he originally wanted to.
I then discovered that there is [already a route](https://github.com/DependencyTrack/frontend/blob/finding-audit-route/src/router/index.js#L134) that …
=> Refactor finding detail and fix finding search routes

src/views/Dashboard.vue
Audited Violations Percentage and Audited Findings Percentage were being incorrectly calculated due to a typo.
Uses the correct properties to calculate the percentages
Using mocked data
**Before**
**After**
=> fix: correctly calculate audited violations and audited findings percentages

src/views/Dashboard.vue
Add footer to the existing `Policy Violations` card, similar to that of `Portfolio Vulnerabilities` that shows the current metrics for fail, warn and info policy violations.
Displays current metrics to help with usability and clarity.  
Current functionality is quite fiddly to hover-over the chart and get the current policy violation metrics
Example using mocked data
=> feat(violations): add current fail, warn, info metrics to footer

src/shared/common.js
Refactor `calcProgressPercent` to found to the tenth decimal place, as per the functions comment/description.
```
/**
* Given a total number of something and a lower number that is completed,
* function will return a percentage rounded to the tenth decimal place.
*/
```
Also changed the order of the if statements to better flow.
Previous logic was rounding to the nearest integer.
Previous logic
=> fix(common): calculate percentage to tenth decimal place

src/views/Dashboard.vue
Use consistent color (warning/yellow) for `Suppressed` portfolio statistics.  This matches the color used by the suppressed toggle
=> refactor(dashboard): use consistent color for suppressed

src/assets/scss/_custom.scss, src/views/Dashboard.vue
Set progress colors using SCSS, so that colors are consistent and centrally managed via _variables.scss propertie.
This helps setup future PRs for dashboard footers that will use non-standard bootstrap progress variant colors (ie: severity high which is `orange`)
=> refactor(dashboard): set progress colors via scss

src/assets/scss/_variables.scss, src/i18n/locales/en.json, src/views/Dashboard.vue, src/views/dashboard/ChartComponentVulnerabilities.vue, src/views/dashboard/ChartProjectVulnerabilities.vue
Add non-vulnerable metrics to Projects and Components charts.
Add footer metrics to Projects and Components cards.
=> feat(dashboard): add vuln / non-vuln footer to projects and components cards

src/i18n/locales/en.json, src/views/portfolio/projects/ProjectDetailsModal.vue
Improve clarity around project active status and sync label on switch changes
Improve the UX around the `Active` / `Inactive` switch under `Project Details`
=> refactor(project details): improve UX for active/inactive toggle.

src/shared/common.js
Handle edge cases better when calculating percentages and progress.
When starting a new instance, percentages were being calculated as `100%`
=> refactor: handle percentage calc edge cases

src/views/portfolio/vulnerabilities/AffectedProjects.vue, src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Adds support to toggle active / inactive affected project details.
Closes #722 
Required backend changes: https://github.com/DependencyTrack/dependency-track/pull/3425
=> feat(vulnerabilities): support active/inactive affected projects

src/views/portfolio/projects/ProjectComponents.vue
Fixes "Outdated Only" button being disabled when dependency graph is not available.
Fixes https://github.com/DependencyTrack/dependency-track/issues/3404
N/A
=> Fix "Outdated Only" button being disabled when dependency graph is not available

src/views/portfolio/projects/ProjectComponents.vue
Fixes redundant requests to `/api/v1/component` when loading project page.
`onlyOutdated` and `onlyDirect` were initialized with non-boolean values. Both variables have a watch on them, triggering a refresh of the components table upon change. Both variables are used as model for `c-switch` components, causing their value to transition to `false` immediately, triggering the watches and consequently table refreshes.
This behavior could cause requests to be abandoned before their content was fully consumed, resulting in `EofException`s in the API server.
Abandoned requests are also visible in the Network tab of the browser:
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) …
=> Fix redundant requests to `/api/v1/component` when loading project page

src/shared/utils.js
Fixes table column visibility preferences triggering redundant requests.
N/A
When applying user preferences for column visibility, fields of the bootstrap table were accessed directly. Apparently the bootstrap table has watches on those fields, which caused table contents to be loaded at least twice, instead of once.
This does not happen when using the "official" `table.showColumn` / `table.hideColumn` methods. Switching to those no longer causes duplicate requests.
=> Fix table column visibility preferences triggering redundant requests

src/i18n/locales/en.json, src/views/administration/configuration/Email.vue
- Email Subject Prefix is Hardcoded rightnow `.subject("[Dependency-Track] " + notification.getTitle())`, 
- This is a solution to allow the User to modify the Subject Prefix to its will  `.subject(smtpPrefix + " " + notification.getTitle() )`
This modification would be available in `Administration>Configuration>Email` 
and ` "[Dependency-Track]"` would be the first default value. 
If the User change the Subject Prefix, it will need to press Update button in order to save the changes.
Subject Prefix is **not a required field** so leaving the input box in blank is also an option.
**_This new feature helps to distinguish between several instances of Dependency-Track, e.g. prod and qual systems._**
This PR depends on its corresponding PR in the **server** repository …
=> New Subject Prefix Input Box

src/views/components/SeverityProgressBar.vue, src/views/portfolio/projects/ProjectList.vue
Add tooltips to the Project List vulnerability progress bar
Match behavior of Policy Violations progress bar tooltips.  Improves UX for seeing metrics without clicking through.
=> feat(project): add tooltip to vuln progress bar

src/assets/scss/_custom.scss, src/i18n/locales/en.json, src/views/portfolio/projects/Project.vue
It was pointed out in Slack, that the Audit Vulnerabilities was showing a total, inclusive of aliases.
This PR adds two badges, one for total including aliases, another for total excluding aliases.  I have also added some descriptive tooltips
Clarifies the total badge figure, which previously conflicted with the sum of the 5 vulnerability pie charts
=> feat(project): finding badges including and excluding aliases

package-lock.json, package.json
Add @vue/runtime-dom as devDependency
Resolves VSCode / Vue Doctor warning
> @vue/runtime-dom missing for Vue 2
> Vue 2 does not have JSX type definitions, so template type checking will not work correctly. You can resolve this problem by installing @vue/runtime-dom and adding it to your project's devDependencies.
=> build: add @vue/runtime-dom as devDependency

src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
Do not append `@<version>` when rendering CPEs in Affected Components view.
Fixes #747
Also cleaned up how ranges are rendered. Previously, ranges with only upper bounds would be rendered as `(|<x.y.z)`, now they're rendered as `(<x.y.z)`.
=> Do not append `@<version>` when rendering CPEs in Affected Components view

package-lock.json, package.json
Update @cyclonedx/cyclonedx-npm package so remove npm engine warning
When building with npm10, the following warning is displayed
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@cyclonedx/cyclonedx-npm@1.13.0',
npm WARN EBADENGINE   required: { node: '>=14', npm: '6 - 9' },
npm WARN EBADENGINE   current: { node: 'v20.11.1', npm: '10.4.0' }
npm WARN EBADENGINE }
```
=> chore: bump cyclonedx-npm package for npm10 support

.github/workflows/lint.yaml, src/shared/common.js, src/views/portfolio/projects/ComponentDetailsModal.vue, src/views/portfolio/projects/ComponentVulnerabilities.vue, src/views/portfolio/projects/ProjectDependencyGraph.vue, src/views/portfolio/projects/ProjectDetailsModal.vue, src/views/portfolio/projects/ProjectFindings.vue, src/views/portfolio/projects/ServiceDetailsModal.vue, src/views/portfolio/vulnerabilities/VulnerabilityList.vue
The linting step wasn't being run on pushes to master
=> feat: lint on master

src/views/portfolio/projects/ProjectList.vue
Fixes `Components` column erroneously being sortable.
Unfortunately, due to technical limitations, it's not possible to sort by the number of components on the server-side.
Fixes #764
N/A
=> Fix `Components` column erroneously being sortable

src/App.vue, src/views/portfolio/projects/ProjectUploadBomModal.vue, src/views/portfolio/projects/ProjectUploadVexModal.vue
Handles BOM validation errors as introduced in https://github.com/DependencyTrack/dependency-track/pull/3522.
Instead of displaying a generic error message for all responses with status code >= 400, display a human-readable error description when RFC 9457 problem details are returned.
Relates to https://github.com/DependencyTrack/dependency-track/issues/3218
Individual validation errors are returned by the API, but not currently displayed by the frontend. This is because multiple validation errors can be returned, and each error message can be rather long. We simply don't have the screen real-estate at the moment to display all of that.
- ~This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/mast …
=> Handle BOM validation errors

src/views/administration/accessmanagement/ApiKeyListGroupItem.vue, src/views/administration/accessmanagement/EditApiKeyCommentModal.vue
Fixes API key rows not being displayed.
The keyword `this` is not available when using `() => {}` notation instead of `function() {}`...
This is a regression introduced in #768. Thanks @msymons for spotting it!
N/A
N/A
=> Fix API key rows not being displayed

src/views/administration/accessmanagement/PortfolioAccessControl.vue
Fix link to projects in Portfolio Access Control view
Fixes #676
=> Fix link to projects in Portfolio Access Control view

src/views/portfolio/components/ComponentSearch.vue
Add new column called `Internal` to display the component `isInternal` value as a checkbox. 
Previously, the component search list view did not display an indicator of whether it was internal/external.
=> feat(component): add internal column to component search list view

src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Add Neccesary parameter to resolveVulnAliases function
common.resolveVulnALiases needs the vulnerability source and the aliases to deduplicate the list on the Aliases column,
The only parameter added to the function was "value" which do not include neither the source of the current vulnerability or their aliases.
Thats why I am adding row.source and row.aliases to the function.
I discovered that the 'return' statement was located within the condition if(typeof value !== 'undefined'), This created a problem because the function would not return anything for null values. To fix this, I moved the 'return' outside of the condition.
#765
=> Aliases column is not displaying information in Vulnerabilities section

README.md, package.json, src/views/components/AboutModal.vue
As per [internal discussion](https://owasp.slack.com/archives/C04FL64RPK9/p1710942680826329), this PR transfers copyright from Steve Springett to the OWASP Foundation.
N/A
N/A
=> Transfer copyright from Steve Springett to OWASP Foundation

src/views/administration/AdminMenu.vue
Fixes startup warning
```
Module Warning (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) <router-link v-for="item in section.children">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
@ ./src/views/administration/AdminMenu.vue?vue&type=template&id=45a3a857&scoped=true& 1:0-438 1:0-438
@ ./src/views/administration/AdminMenu.vue
@ ./node_modules/babel-loader/lib??ref--12-0!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/administration/Administration.vue?vue&type=script&lang=js&
@ ./src/views/administration/Administration.vue?vue&type=script&lang=js&
@ …
```
=> fix: v-for explicit key

src/assets/scss/vendors/bootstrap/_variables.scss
Address build warnings by running https://sass-lang.com/documentation/breaking-changes/slash-div/#automatic-migration
Address a number of warnings such as the example below
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
Recommendation: math.div(4em, 14) or calc(4em / 14)
More info and automated migrator: https://sass-lang.com/d/slash-div
```
=> refactor: perform saas slash-div migration

src/views/portfolio/licenses/LicenseList.vue
Add deprecated column to the License List view
=> feat(license): add deprecated column

src/views/portfolio/projects/ComponentDetailsModal.vue, src/views/portfolio/projects/ProjectDetailsModal.vue, src/views/portfolio/projects/ServiceDetailsModal.vue
A column to display the `comment` field has been added to the `External References` tab in Component Details, Project Details and Service Details modals
Fixes #802
=> Add Comment Column To External References

src/views/portfolio/components/ComponentSearch.vue
Add license column to the component search screen
#567
=> feat(component-search): add license column

src/i18n/locales/de.json, src/i18n/locales/en.json, src/i18n/locales/es.json, src/i18n/locales/fr.json, src/i18n/locales/hi.json, src/i18n/locales/it.json, src/i18n/locales/ja.json, src/i18n/locales/pl.json, src/i18n/locales/pt-BR.json, src/i18n/locales/pt.json, src/i18n/locales/ru.json, src/i18n/locales/zh.json, src/views/portfolio/vulnerabilities/Vulnerability.vue
Adds the raw EPSS score and percentile numbers to the vulnerability details page, similar to the CVSS Exploit Score and other metrics.
Fixes #544 
Initially thought of converting both the numbers into percentage by multiplying by 100 for readability (Would have to use .toFixed(2) to avoid JS floating point multiplication precision issue). But kept them as the raw number itself since that's how the [EPSS data by FIRST](https://www.first.org/epss/data_stats) is reported.
=> Display EPSS Score And Percentile In Vulnerability Page

src/views/components/LocalePicker.vue
Forces page reload after locale change.
This is necessary because not all UI elements are updated automatically when the locale is changed. In order to avoid mixed i18n, or having users do the refresh themselves, we do it automatically for now.
N/A
N/A
=> Force page reload after locale change

.github/workflows/_meta-build.yaml, .github/workflows/ci-build.yaml, .github/workflows/ci-publish.yaml, .github/workflows/codeql-analysis.yaml, .github/workflows/i18n.yaml, .github/workflows/lint.yaml
Runs builds and CI on `feature-*` branches.
This allows contributors to collaborate on branches that are not `master`, and still profit from CI runs and container images being published.
Names of feature branches are required to be prefixed with `feature-`. Container images built from them will be published using the branch name as tag.
https://github.com/DependencyTrack/dependency-track/issues/2972
API server PR: https://github.com/DependencyTrack/dependency-track/pull/3672
=> Run builds and CI on `feature-*` branches

src/views/portfolio/projects/Project.vue
If a project has many versions, the versions dropdown should be scrollable such that the user can view and select any desired version.
**Demo Video**
https://github.com/DependencyTrack/frontend/assets/43161107/682612be-5677-498e-ad3d-ccd51031a8d1
Fixes #809 
The `.dropdown-menu` class was referenced in the `<ul>` but not defined, so decided to use that class itself.
=> Restrict Height Of Project Versions Dropdown

src/views/portfolio/projects/Project.vue
In the project versions dropdown, moved all the inactive versions towards the bottom of the list, grouped underneath a heading "Inactive Versions". This provides clear separation between active and inactive versions.
Fixes #844 
**Prerequisite**: The below backend PR needs to be merged for this change to work.
https://github.com/DependencyTrack/dependency-track/pull/3691
In the dropdown, I didn't add a group/heading called "Active Versions" since I felt it was implicit, but happy to update as necessary.
=> Distinguish Between Active And Inactive Project Versions

src/views/portfolio/components/ComponentSearch.vue, src/views/portfolio/projects/ProjectComponents.vue, src/views/portfolio/projects/ProjectServices.vue
When instantiating the `SeverityProgressBar` ComponentClass, the `$t` prop for `i18n` should be passed to it, so that the messages in the tooltip of the progress bar are rendered.
**Screenshot of result:**
Fixes #867 
I noticed that it was working fine in `ProjectList`, so referred how it was done there and replicated the same where ever `SeverityProgressBar` is used
=> Bind i18n Object To SeverityProgressBar Props

src/views/portfolio/components/ComponentSearch.vue, src/views/portfolio/projects/ProjectComponents.vue, src/views/portfolio/projects/ProjectServices.vue
When instantiating the `SeverityProgressBar` ComponentClass, the `$t` prop for `i18n` should be passed to it, so that the messages in the tooltip of the progress bar are rendered.
**Screenshot of result:**
Fixes #867
Backports #871
I (@aravindparappil46) noticed that it was working fine in `ProjectList`, so referred how it was done there and replicated the same where ever `SeverityProgressBar` is used
=> Backport: Bind i18n Object To SeverityProgressBar Props

docker/Dockerfile.alpine
Bumps nginxinc/nginx-unprivileged from `5b42062` to `8265b1d`.
=> Backport: build(deps): bump nginxinc/nginx-unprivileged in /docker

src/views/administration/notifications/Alerts.vue
Since `BOM_VALIDATION_FAILED` has been added as a notification, users need to be able to select it from the UI for each notification channel
Fixes https://github.com/DependencyTrack/dependency-track/issues/3778
=> Add BOM_VALIDATION_FAILED To Notification Group

src/views/portfolio/projects/ComponentVulnerabilities.vue
Toggle the `sortable` flag for columns "Severity" and "CWE" as the API server [supports sorting since v4.11](https://github.com/DependencyTrack/dependency-track/issues/708#issuecomment-2081583356).
Resolves DependencyTrack/dependency-track#708
> No sorting behavior exists in the Components' Vulnerability tab on the Severity, like in the Projects tab.
- ~[ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~
=> Sort Components Vulnerabilities by Severity or CWE

src/views/administration/accessmanagement/SelectProjectModal.vue, src/views/portfolio/tags/TaggedProjectListModal.vue
Makes tagged project names clickable.
Also fixes broken project links in `SelectProjectModal` for portfolio ACL.
Relates to https://github.com/DependencyTrack/dependency-track/issues/586
N/A
=> Make tagged project names clickable

src/views/portfolio/projects/ProjectCreateProjectModal.vue, src/views/portfolio/projects/ProjectDetailsModal.vue
Adds support for autocomplete in tag input fields.
Relates to https://github.com/DependencyTrack/dependency-track/issues/586
N/A
=> Add autocomplete support for tag inputs

src/views/policy/PolicyList.vue, src/views/portfolio/tags/TaggedPoliciesListModal.vue
Replaces usages of `/api/v1/policy/{uuid}/tag/{name}` endpoints with `/api/v1/tag/{name}/policy`, in accordance with DependencyTrack/dependency-track#3924.
Also fixes redundant toasts when removing or adding tags from/to policies.
Adds ability to untag policies from *Tags* view:
The *Remove* button is visible to users with `POLICY_MANAGEMENT` permission.
Relates to https://github.com/DependencyTrack/dependency-track/issues/586
N/A
=> Fix usage of deprecated policy tagging endpoints, and add ability to untag policies from *Tags* view

docker/Dockerfile.alpine
Bumps the `nginxinc/nginx-unprivileged` base image to 1.27.0.
Resolves a few vulnerabilities in OS packages.
N/A
=> Backport: Bump `nginxinc/nginx-unprivileged` to 1.27.0

package-lock.json, package.json
Bumps `bootstrap-table` to 1.22.6.
Fixes the `sort` event not being triggered when clicking table columns.
https://bootstrap-table.com/news/
N/A
N/A
=> Bump `bootstrap-table` to 1.22.6

docker/Dockerfile.alpine
Bumps `nginxinc/nginx-unprivileged` to `bb3225a`.
Resolves 14 CVEs in the base image.
Backports #961
N/A
=> Bump `nginxinc/nginx-unprivileged` to `bb3225a`

src/views/administration/configuration/EmailTestConfigurationModal.vue, src/views/administration/notifications/Alerts.vue
Add a button to the notifications settings to test the publisher.
Back-end implementation: https://github.com/DependencyTrack/dependency-track/pull/3983
https://github.com/DependencyTrack/dependency-track/issues/2924
=> Add ability to test notification publishers

src/views/portfolio/projects/Project.vue, src/views/portfolio/projects/ProjectPolicyViolations.vue
Dependent on https://github.com/DependencyTrack/dependency-track/pull/3615
Display the policy violations badge metrics (total, fail, warn, info) based on the showSuppressed flag.
=> feat: dynamic policy violation badges based on show suppressed flag

src/containers/DefaultContainer.vue
Used LocalStorage to store the expanded
state of the sidebar, so it persists over sessions
Fixes [#864](https://github.com/DependencyTrack/frontend/issues/864)
Loads state out of LocalStorage and applies it. Then Sidebar is toggled, it gets saved in localStorage over an additional click event handler method.
~~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~~
=> feat/Save Sidebar state in local storage

src/App.vue
Fixes links with `href="#"` being pushed to Vue router.
Fixes #1011
N/A
=> Fix links with `href="#"` being pushed to Vue router

src/views/administration/accessmanagement/Teams.vue
Adds Oidc user to Team view, similar to the sheme of the other users.
Fixes #1033
N/A
=> fix: Add Oidc user to team view

src/containers/DefaultContainer.vue
State before was only in Snapshot version saved/loaded in/from local storage.
Fixes #1031
N/A
=> State should now also in not Snapshot version saved

.gitattributes
Adds `.gitattributes` to fix prettier behavior on Windows.
Backports https://github.com/DependencyTrack/frontend/pull/1042
N/A
=> Backport: Add `.gitattributes` to fix prettier behavior on Windows

src/containers/DefaultContainer.vue
Fixes state of sidebar not being saved for non-`SNAPSHOT` versions.
Fixes https://github.com/DependencyTrack/frontend/issues/1031
Backports https://github.com/DependencyTrack/frontend/pull/1032
N/A
=> Backport: Fix state of sidebar not being saved for non-`SNAPSHOT` versions

src/views/portfolio/projects/ProjectCreateProjectModal.vue
Fixes creation of multiple projects without reloading page.
Fixes https://github.com/DependencyTrack/frontend/issues/1025
Backports https://github.com/DependencyTrack/frontend/pull/1028
N/A
=> Backport: Fix creation of multiple projects without reloading page

docker/etc/nginx/templates/default.conf.template
Disables caching for `index.html` and `config.json`. Assets (i.e. CSS, JS files) already have a unique value in their name for cache busting across builds.
Fixes #860
N/A
=> Fix caching issues upon upgrade

src/views/portfolio/projects/ProjectDependencyGraph.vue
Always display project nodes in dependency graph using name and version.
Fixes #1026
Backports https://github.com/DependencyTrack/frontend/pull/1048
N/A
=> Backport: Always display project nodes in dependency graph using name and version

docker/etc/nginx/templates/default.conf.template
Disables caching for index.html and config.json. Assets (i.e. CSS, JS files) already have a unique value in their name for cache busting across builds.
Fixes https://github.com/DependencyTrack/frontend/issues/860
Backports https://github.com/DependencyTrack/frontend/pull/1050
N/A
=> Backport: Fix caching issues upon upgrade

src/views/portfolio/projects/ProjectAddVersionModal.vue
I have added a fix to keep the create button inactive until a value is provided in the version input field. This is to improve the form's UX and prevent invalid submissions.
Fixes #995
=> Fix: "Add Version" Create Button Should Be Inactive Until Version Provided

src/views/portfolio/projects/ProjectAddVersionModal.vue
Fix: "Add Version" Create Button Should Be Inactive Until Version Provided.
Fixes https://github.com/DependencyTrack/frontend/issues/995
Backports https://github.com/DependencyTrack/frontend/pull/1039
N/A
=> Backport: Fix: "Add Version" Create Button Should Be Inactive Until Version Provided

src/views/portfolio/tags/TagList.vue, src/views/portfolio/tags/TaggedNotificationRuleListModal.vue, src/views/portfolio/tags/TaggedPoliciesListModal.vue, src/views/portfolio/tags/TaggedProjectListModal.vue
Fixes missing URI encoding of tag names.
The *tagged projects*, *tagged policies*, and *tagged alerts* dialogs would show an empty list for tags that contain special characters such as `/`.
This was caused by both https://github.com/DependencyTrack/dependency-track/issues/4238, and tag names not being URI-encoded prior to using them as path parameters.
N/A
N/A
=> Fix missing URI encoding of tag names

src/views/portfolio/tags/TagList.vue, src/views/portfolio/tags/TaggedNotificationRuleListModal.vue, src/views/portfolio/tags/TaggedPoliciesListModal.vue, src/views/portfolio/tags/TaggedProjectListModal.vue
Fixes missing URI encoding of tag names.
Backports https://github.com/DependencyTrack/frontend/pull/1056
N/A
=> Backport: Fix missing URI encoding of tag names

docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
The templating of the nginx config overrides the changes made by the IPv6 init script. This PR instead changes the template file.
None
Initial implementations:
- https://github.com/DependencyTrack/frontend/pull/427
- https://github.com/DependencyTrack/frontend/pull/621
Broken by: https://github.com/DependencyTrack/frontend/pull/801
=> docker: fix ipv6 listening

src/views/portfolio/projects/ComponentDetailsModal.vue, src/views/portfolio/projects/ComponentPropertiesModal.vue
With this change Users with the `VIEW_PORTFOLIO` permission can see the component properties.
Previously the button to `Properties` in the component details modal was not shown to users not having the `PORTFOLIO_EDIT` permission.
AFAIK there is no issue for this.
Details view after Change only with `VIEW_PORTFOLIO` permission:
Property view only with `VIEW_PORTFOLIO` permission:
=> Show component properties to users with VIEW_PORTFOLIO permission

src/views/administration/configuration/WelcomeMessage.vue
Fixes no error being displayed when submitting an invalid welcome message.
Fixes https://github.com/DependencyTrack/frontend/issues/1090
Backports #1091
N/A
=> Backport: Fix no error being displayed when submitting an invalid welcome message

src/views/portfolio/tags/TagList.vue
Fixes tags with special characters breaking the tags table.
Fixes #1081
Backports #1082
N/A
=> Backport: Fix tags with special characters breaking the tags table

src/views/portfolio/projects/ProjectCreateProjectModal.vue
Prefills *Team* input in *Create Project* dialog based on user's team membership.
Fixes https://github.com/DependencyTrack/frontend/issues/1088
Backports https://github.com/DependencyTrack/frontend/pull/1089
N/A
Signed-off-by: Thomas Schauer-Koeckeis <thomas.schauer-koeckeis@rohde-schwarz.com>
=> Backport: Prefill *Team* input in *Create Project* dialog based on user's team membership

src/views/portfolio/vulnerabilities/AffectedProjects.vue
The affected projects tab (and table) is not updated correctly when switching between aliases.
fixes #481
I'm leaving this as a draft for now because there is also a backend issue that should be fixed first (see https://github.com/DependencyTrack/frontend/issues/481#issuecomment-1568924285).
=> Fix affected projects tab not being updated when switching between vulnerability aliases

src/views/portfolio/vulnerabilities/AffectedProjects.vue
Fixes affected projects tab not being updated when switching between vulnerability aliases.
Fixes #481
N/A
=> Port: Fix affected projects tab not being updated when switching between vulnerability aliases

src/views/dashboard/ChartAuditingFindingsProgress.vue, src/views/dashboard/ChartAuditingViolationsProgress.vue, src/views/dashboard/ChartComponentVulnerabilities.vue, src/views/dashboard/ChartPolicyViolationsClassification.vue, src/views/dashboard/ChartPolicyViolationsState.vue, src/views/dashboard/ChartPortfolioVulnerabilities.vue, src/views/dashboard/ChartProjectVulnerabilities.vue, src/views/dashboard/WidgetInheritedRiskScore.vue, src/views/dashboard/WidgetPortfolioVulnerabilities.vue, src/views/dashboard/WidgetProjectsAtRisk.vue, src/views/dashboard/WidgetVulnerableComponents.vue
Previously chart tooltips only showed dates without time information, making it difficult to correlate chart events with specific times. This change adds proper timestamp formatting (including HH:mm:ss) to tooltips across all chart components.
The changes include:
- Added timestamp formatting in chart tooltips using common.formatTimestamp()
- Applied consistent formatting across all chart components
- Maintained existing date formatting on x-axis labels
This addresses issue #1142 which requested adding timestamp information to make it easier to investigate events shown in charts.
Added timestamp (HH:mm:ss) formatting to all chart tooltips to help users better
correlate visualization data points with system events. This enhancement makes it
easier to investigate peaks, troughs, and step …
=> Add timestamp formatting to chart tooltips

src/views/portfolio/projects/Project.vue
Fixes policy violation tab indicators being populated incorrectly.
Fixes #1170
Backports #1171
N/A
=> Backport: Fix policy violation tab indicators being populated incorrectly

docker/Dockerfile.alpine
Bumps nginxinc/nginx-unprivileged from 1.27.3-alpine to 1.27.4-alpine.
Resolves a few CVEs in the base image.
N/A
=> Bump nginxinc/nginx-unprivileged from 1.27.3-alpine to 1.27.4-alpine

src/views/portfolio/projects/Project.vue
Fixes wrong policy violation tab indicator visibility conditions.
Relates to #1170
Relates to #1171
Backports #1174
N/A
=> Backport: Fix wrong policy violation tab indicator visibility conditions

src/assets/scss/vendors/vue-tags-input/_vue-tags-input.scss
Updated tag dropdown autocomplete's style selector to prevent the input library's style overriding the custom style from the app which made it hard to read due to low contrast
Closes: #1146 
The issue is caused by the library's default style occasionally overriding the custom style.
`.ti-autocomplete` is always a `div` tag [(source code)](https://github.com/JohMun/vue-tags-input/blob/294026aeed583154df3aeaf9f8007136404c132e/vue-tags-input/vue-tags-input.vue#L150-L154) so added the tag name to the style selector to override the default style.
=> Fix tag autocomplete dropdown library style overriding issue

src/views/portfolio/projects/ProjectCreateProjectModal.vue, src/views/portfolio/projects/ProjectDetailsModal.vue
Added autocomplete to Project Collection Logic's tags dropdown to make the UX consistent as "Tags" dropdown within the same modal.
Closes: #1147  
- Updated `searchTags` method to receive the input string as a parameter so the method can be used for both collection tag and project tag.
- Tag dropdowns share `tagsAutoCompleteItems` for autocomplete list since only one dropdown can be focused at a time.
Autocomplete screenshot:
=> Add autocomplete to project collection logic tag dropdown

src/i18n/locales/de.json, src/i18n/locales/en.json, src/i18n/locales/es.json, src/i18n/locales/fr.json, src/i18n/locales/hi.json, src/i18n/locales/it.json, src/i18n/locales/ja.json, src/i18n/locales/pl.json, src/i18n/locales/pt-BR.json, src/i18n/locales/pt.json, src/i18n/locales/ru.json, src/i18n/locales/uk-UA.json, src/i18n/locales/zh.json, src/views/portfolio/projects/ProjectDashboard.vue
Displays last vuln analysis timestamp in project view.
The timestamp field was added to the project model in https://github.com/DependencyTrack/dependency-track/issues/4620.
N/A
=> Display last vuln analysis timestamp in project view

docker/Dockerfile.alpine
Bumps nginxinc/nginx-unprivileged from 1.27.4-alpine to 1.27.5-alpine.
Backports https://github.com/DependencyTrack/frontend/pull/1238
N/A
=> build(deps): bump nginxinc/nginx-unprivileged from 1.27.4-alpine to 1.27.5-alpine in /docker

src/i18n/locales/de.json, src/i18n/locales/en.json, src/i18n/locales/es.json, src/i18n/locales/fr.json, src/i18n/locales/hi.json, src/i18n/locales/it.json, src/i18n/locales/ja.json, src/i18n/locales/pl.json, src/i18n/locales/pt-BR.json, src/i18n/locales/pt.json, src/i18n/locales/ru.json, src/i18n/locales/uk-UA.json, src/i18n/locales/zh.json, src/views/portfolio/tags/TagList.vue, src/views/portfolio/tags/TaggedCollectionProjectListModal.vue
Shows collection projects using tag in tag list.
Relates to https://github.com/DependencyTrack/dependency-track/pull/4858
Backports https://github.com/DependencyTrack/frontend/pull/1237
N/A
=> Show collection projects using tag in tag list

src/views/policy/LicenseGroupList.vue
=> feat: display license id
