- src/assets/scss/_variables.scss
- src/views/portfolio/projects/Projects.vue
> Fetch projects list from API

- src/forms/BValidatedInputGroupFormInput.vue
- src/i18n/messages.json
- src/validation/index.js
- src/views/pages/Login.vue
- src/views/pages/PasswordForceChange.vue
This PR refactors validation to happen in separate form input components. It also adds more thorough validation to the password force change flow
> Refactor validation to a separate component

- src/i18n/locales/en.json
- src/views/administration/notifications/Alerts.vue
> Use the group word for notification group

- src/i18n/locales/en.json
- src/views/administration/AdminMenu.vue
- src/views/administration/Administration.vue
- src/views/administration/repositories/Composer.vue
- src/views/administration/repositories/RepositoryCreateRepositoryModal.vue
The UI changes for the PR https://github.com/DependencyTrack/dependency-track/pull/796 and the issue https://github.com/DependencyTrack/dependency-track/issues/356
Thank you for taking your time to review this PR, it is much appreciated.
> adding Composer repository support

- src/i18n/locales/en.json
- src/views/policy/PolicyCondition.vue
Companion PR for https://github.com/DependencyTrack/dependency-track/pull/930
> Add support for version policy conditions

- package-lock.json
- package.json
- src/main.js
- src/router/index.js
- src/views/portfolio/licenses/License.vue
- src/views/portfolio/projects/Component.vue
- src/views/portfolio/projects/Project.vue
- src/views/portfolio/vulnerabilities/Vulnerability.vue
This adds page titles of type "Dependency-Track - xxx" for static pages and dynamic content such as projects, vulnerabilities, components and licenses.
fixes #55
> Add meaningful page titles

- src/views/pages/Login.vue
Addresses https://github.com/DependencyTrack/dependency-track/issues/1008. 
Companion PR for https://github.com/stevespringett/Alpine/pull/185 and https://github.com/DependencyTrack/dependency-track/pull/1032
> Pass ID token to API server during OIDC login

- src/i18n/locales/en.json
- src/views/administration/AdminMenu.vue
- src/views/administration/Administration.vue
- src/views/administration/repositories/GoModules.vue
- src/views/administration/repositories/RepositoryCreateRepositoryModal.vue
Companion PR for https://github.com/DependencyTrack/dependency-track/pull/1110
> Add repository support for Go Modules

- src/views/portfolio/projects/ProjectUploadBomModal.vue
> Disable upload BOM button when no file selected

- src/shared/common.js
The analysis status is now displayed in the policy violations tab table
> Fixed analysis status display in policy violations tab

- src/i18n/locales/en.json
> Fixed spelling mistake

- src/i18n/locales/en.json
make it clear it's just a PAT and no scope is needed
> text: github advisories: explain type of token needed

- src/views/portfolio/projects/ProjectFindings.vue
> Fix analysis justification and response being reset when suppressing a finding

- src/views/administration/vuln-sources/VulnSourceNvd.vue
Fixes #137 and DependencyTrack/dependency-track#1576
> Fix NVD properties not saving (fixes #137)

- src/views/portfolio/projects/ComponentVulnerabilities.vue
- src/views/portfolio/vulnerabilities/VulnerabilityCreateVulnerabilityModal.vue
- src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
- src/views/portfolio/vulnerabilities/VulnerabilityList.vue
> Fix usages of `cwe` field instead of `cwes`

- src/views/administration/accessmanagement/OidcGroups.vue
- src/views/administration/accessmanagement/Teams.vue
- src/views/administration/repositories/Repositories.vue
- src/views/policy/LicenseGroupList.vue
- src/views/policy/PolicyList.vue
Addresses https://github.com/DependencyTrack/frontend/issues/98
Signed-off-by: ege-dw <enora.germond@deveryware.com>
> Resume focus after saving

- src/views/policy/PolicyList.vue
Addresses https://github.com/DependencyTrack/frontend/issues/169
Signed-off-by: ege-dw <enora.germond@deveryware.com>
> fix missing update of UI when restricting a policy

- src/i18n/locales/en.json
- src/views/policy/PolicyCondition.vue
Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>
Issue: https://github.com/DependencyTrack/dependency-track/issues/1768
Backend: https://github.com/DependencyTrack/dependency-track/pull/1773
> Issue-1768: policy condition cwe

- src/i18n/locales/en.json
- src/views/policy/PolicyCondition.vue
Issue: https://github.com/DependencyTrack/dependency-track/issues/1775
https://github.com/DependencyTrack/dependency-track/issues/1553
backend: https://github.com/DependencyTrack/dependency-track/pull/1776
> Issue 1775 : policy condition - component hash

- src/i18n/locales/en.json
- src/views/administration/notifications/CreateAlertModal.vue
- src/views/administration/notifications/CreateTemplateModal.vue
- src/views/administration/notifications/GeneralTemplateConfigurationModal.vue
- src/views/administration/notifications/Templates.vue
Notification template enhancement as described in DependencyTrack/dependency-track#275
Signed-off-by: Alioune SY <sy_alioune@yahoo.fr>
First of all, thank you for developing and maintaining such a great solution.
Please find below related to PR to review :
Backend : [PR 1760](https://github.com/DependencyTrack/dependency-track/pull/1760) 
Alpine : [PR 403](https://github.com/stevespringett/Alpine/pull/403)
**Override default templates**
**Restore default templates**
**Create publisher**
**Publisher listing : Default and non default**
**Modify non default publisher**
> Make notification template editable

- .github/dependabot.yml
> Configure dependabot to include Docker and GHA dependencies

- src/views/administration/accessmanagement/Teams.vue
> Fix minor API keys display issues

- src/i18n/locales/en.json
- src/views/administration/vuln-sources/VulnSourceOSVAdvisories.vue
Signed-off-by: Sahiba Mittal <sahibamittal98@gmail.com>
Issue: https://github.com/DependencyTrack/dependency-track/issues/1964
> Issue 1964: OSV base url customised

- src/views/portfolio/projects/ComponentVulnerabilities.vue
Make more information available on the component vulnerability tab with default visibility false.
Fixes DependencyTrack/dependency-track#1948
Signed-off-by: awegg <alexander@weggerle.de>
> Add CVSS, EPSS to Component Vulnerabilities

- src/views/administration/notifications/Alerts.vue
https://github.com/DependencyTrack/dependency-track/issues/1611
> Re-enable NEW_VULNERABLE_DEPENDENCY notification

- src/i18n/locales/en.json
- src/views/administration/AdminMenu.vue
- src/views/administration/Administration.vue
- src/views/administration/configuration/JiraConfig.vue
- src/views/administration/notifications/Alerts.vue
> Add new admin vues to configure Jira alerts

- src/i18n/locales/en.json
- src/validation/index.js
- src/views/administration/AdminMenu.vue
- src/views/administration/Administration.vue
- src/views/administration/configuration/Search.vue
Allow selective lucene indexex rebuild through admin screen
DependencyTrack/dependency-track#2104
Still to be done :
- Description completion on the admin screen
- Documentation update
~~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~~
> Feature: Enable lucene index rebuild through UI

- .github/ISSUE_TEMPLATE/defect-report.yml
Bump the available versions in the "Defect Report" issue template.
N/A
N/A
> Bump versions in issue template

- src/views/portfolio/projects/ProjectPolicyViolations.vue
This PR backports #372 to 4.7.1.
#373
N/A
> Prepare v4.7.1

- src/i18n/locales/en.json
- src/views/policy/PolicyCondition.vue
Companion PR for https://github.com/DependencyTrack/dependency-track/pull/2419.
https://github.com/DependencyTrack/dependency-track/issues/772
> Add support for component age policy conditions

- src/views/portfolio/projects/ProjectList.vue
This PR introduces a new logic to display the hierarchical view in the `ProjectList` that does not require the `parentUuid` field in `Project`.
[#2439](https://github.com/DependencyTrack/dependency-track/issues/2439)
[Backend PR](https://github.com/DependencyTrack/dependency-track/pull/2470)
~- [ ] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/dependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~
> Remove unnecessary field `parentUuid` in `ProjectList`

- src/views/portfolio/projects/ProjectCreateProjectModal.vue
- src/views/portfolio/projects/ProjectDetailsModal.vue
Addresses https://github.com/DependencyTrack/frontend/issues/168
Signed-off-by: ege-dw <enora.germond@deveryware.com>
> Display added/modified project tags in lowercase

- src/views/portfolio/vulnerabilities/AffectedProjects.vue
Fix a broken link in the Vulnerability -> Affected Projects view.
Fix a broken link in the Vulnerability -> Affected Projects view.
...
> fix affected project(s) link to project

- src/i18n/locales/en.json
- src/router/index.js
- src/views/administration/AdminMenu.vue
- src/views/administration/Administration.vue
- src/views/administration/repositories/Cpan.vue
- src/views/administration/repositories/RepositoryCreateRepositoryModal.vue
Cpan repository support
Closes: https://github.com/DependencyTrack/dependency-track/issues/639
Needs: https://github.com/DependencyTrack/dependency-track/pull/2593
> Cpan repository support

- src/views/administration/notifications/Alerts.vue
This PR adds the new `BOM_PROCESSING_FAILED` notification group from DependencyTrack/dependency-track#2600 to the alerts configuration.
DependencyTrack/dependency-track#2264
> Add `BOM_PROCESSING_FAILED` to alert configuration

- src/i18n/locales/en.json
fix Duplicate Key of 'last_bom_import' in i18n json.
> fix Duplicate Key of 'last_bom_import'

- src/views/portfolio/projects/ProjectList.vue
> Fix: Unable to change page number in project list in some cases when 'show inactive projects' button is clicked

- src/views/portfolio/projects/ProjectDetailsModal.vue
This PR makes the project parent dialogue in the frontend more convenient by offering an empty entry, which removes the current parent relationship. Before, a user had to search for the current parent and had to select it a second time to remove the relationship.
#407
> Make removing parent relationship more convenient

- babel.config.js
- package-lock.json
- package.json
- src/shared/common.js
- src/views/portfolio/projects/ProjectList.vue
Currently tags are not shown in the project list. This PR adds them in a basic way in an optional column:
Signed-off-by: Valentijn Scholten <valentijnscholten@gmail.com>
> project list: show tags

- src/i18n/locales/en.json
- src/views/administration/configuration/JiraConfig.vue
Feat: Support Jira authentication with personal tokens
#462
> Feat: Support Jira authentication with personal tokens

- .github/ISSUE_TEMPLATE/defect-report.yml
Bump version in "Defect Report" issue template, as it was missed during the release of 4.8.0.
N/A
N/A
> Bump version in issue template

- src/views/portfolio/projects/Project.vue
This PR fixes a defect where switching project versions from every tab other than *Overview* would result in a 404.
Fixes #495
N/A
> Fix broken project version dropdown

- src/shared/common.js
- src/views/portfolio/projects/ComponentVulnerabilities.vue
- src/views/portfolio/projects/Project.vue
- src/views/portfolio/projects/ProjectFindings.vue
- src/views/portfolio/projects/ProjectList.vue
- src/views/portfolio/vulnerabilities/Vulnerability.vue
- src/views/portfolio/vulnerabilities/VulnerabilityDetailsModal.vue
- src/views/portfolio/vulnerabilities/VulnerabilityList.vue
This PR backports the following fixes to v4.8.1:
* https://github.com/DependencyTrack/frontend/issues/477
* https://github.com/DependencyTrack/frontend/issues/486
* https://github.com/DependencyTrack/frontend/issues/483
* https://github.com/DependencyTrack/frontend/issues/495
N/A
N/A
> Backport fixes to 4.8.1

- src/router/index.js
- src/shared/permissions.js
Not having JWT was treated the same as not having permission to view the requested page.
Also, a small refactoring was done to make all possible logical paths clearer and the permission check was fixed as well.
fixes #501 
I also took the liberty of simplifying/modernizing `hasPermission` a little.
> fix login redirects

- src/i18n/locales/en.json
- src/views/policy/PolicyCondition.vue
adds a UI for specifying VersionDistance policies to check and report outdated components
closes #431 
Needs https://github.com/DependencyTrack/dependency-track/pull/2537
> UI for new VersionDistance policy to check and report outdated components

- .github/workflows/_meta-build.yaml
- .github/workflows/ci-build.yaml
- .github/workflows/ci-release.yaml
- .github/workflows/codeql-analysis.yaml
- README.md
Upgrade to NodeJS 18 & 20
fixes: #470
> NodeJS 18 & 20

- src/views/components/ExternalReferencesDropdown.vue
- src/views/portfolio/projects/Project.vue
This PR moves the ExternalReferencesDropdown inside of the screen
fixes: #539
> Fix ExternalReferencesDropdown layout

- .github/workflows/codeql-analysis.yaml
- src/views/portfolio/projects/Project.vue
Fixed project versions dropdown by including a list of versions in the API call result.
Fixes: #397
Also added metrics in the API call result and updated UI, to minimize round trips.
Updated some dependencies to get rid of some sonatype-lift warnings, ignored the rest 
Needs: https://github.com/DependencyTrack/dependency-track/pull/2581
> Fix for project versions dropdown

- babel.config.js
- package-lock.json
- package.json
- src/main.js
Use an maintaned version of CoreJS
Fixes: #547
> Upgrade CoreJS to 3.x

- src/views/components/ExternalReferencesDropdown.vue
> Issue #564: Change type of externalReferences component property to 'Array'

- src/mixins/routerMixin.js
- src/views/policy/PolicyList.vue
- src/views/portfolio/licenses/LicenseList.vue
- src/views/portfolio/projects/ProjectList.vue
- src/views/portfolio/vulnerabilities/VulnerabilityList.vue
resolves https://github.com/DependencyTrack/frontend/issues/562
> Issue #562: Propagate searchText query to List views

- src/views/portfolio/projects/ProjectDetailsModal.vue
Fixes external references being cleared when updating a project via UI.
> **Note**  
> Needs to be backported to the `4.9.x` branch.
Fixes #503
N/A
> Fix external references being cleared upon project update

- src/views/portfolio/projects/ProjectDetailsModal.vue
Fixes external references being cleared when updating a project via UI.
Fixes #503
N/A
> Backport: Fix external references being cleared upon project update

- package-lock.json
Backports #629 in order to resolve https://github.com/advisories/GHSA-mpj8-q39x-wq5h.
N/A
N/A
> Backport: bump crypto-js from 4.1.1 to 4.2.0

- babel.config.js
- package-lock.json
- package.json
Bumps `@babel/core` to `7.23.2`, superseding #615.
Additionally removes the dependency on the deprecated `@babel/plugin-proposal-optional-chaining`.
N/A
N/A
> Bump babel to `7.23.2`

- package-lock.json
- package.json
Bumps `axios` to `1.6.0`, and `vue-axios` to `3.5.2`.
N/A
N/A
> Bump `axios` to `1.6.0`; Bump `vue-axios` to `3.5.2`

- package-lock.json
- package.json
Bumps `dompurify` to `2.4.7`.
N/A
N/A
> Bump `dompurify` to `2.4.7`

- src/i18n/locales/en.json
- src/views/administration/repositories/Repositories.vue
- src/views/administration/repositories/RepositoryCreateRepositoryModal.vue
Addresses [issue](https://github.com/DependencyTrack/dependency-track/issues/2870)
Co-authored-by:Sahiba Mittal <sahiba.mittal@citi.com>
> added changes to ui to support authentication for repositories regardless of whether they are for internal packages or not

- src/i18n/locales/en.json
- src/router/index.js
- src/views/administration/AdminMenu.vue
- src/views/administration/Administration.vue
- src/views/administration/repositories/GitHub.vue
Adds GitHub to the repositories menu in the admin panel. This allows users to provide authentication details, or disable the GitHub repository entirely.
N/A
N/A
> Add GitHub to repositories menu

- src/i18n/locales/en.json
- src/views/administration/notifications/Alerts.vue
- src/views/portfolio/projects/ProjectAddVersionModal.vue
This PR introduces a new checkbox when cloning a project (include Policy Violations)
Related to https://github.com/DependencyTrack/dependency-track/pull/3248
#2875
> Project cloning: cloning Policy Violations and ViolatationAnalysis

- src/views/administration/notifications/Alerts.vue
Display the publisher name within the expanded row details.
> feat(notifications): show publisher name on expanded row

- src/i18n/locales/en.json
- src/views/portfolio/projects/Project.vue
Improve the verbiage of the Project Vulnerability pie-chart tooltips to make it clearer
> feat: improve tooltip clarity for project vulnerabilities

- src/assets/scss/_custom.scss
- src/i18n/locales/en.json
- src/views/portfolio/projects/Project.vue
Add badges for policy violation info, warn and fail counts
> feat(project): policy violation badges

- .github/release.yml
- .github/workflows/ci-publish.yaml
- .github/workflows/ci-release.yaml
Adds [auto-generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) to GitHub releases.
Generated notes include all pull requests contained in a given release. PR authors are tagged, giving them proper credit.
> [!NOTE]
> The generated notes are *appended* to the old format, they do not replace it.
N/A
N/A
> Add auto-generated changelog to GitHub releases

- src/views/portfolio/licenses/LicenseList.vue
Use concise license endpoint for consistency with other UI screens
> feat(license): use concise endpoint for license list view

- src/views/portfolio/projects/ProjectComponents.vue
Fixes the *Download BOM* functionality requiring the `PORTFOLIO_MANAGEMENT` permission, even though the underlying REST endpoint only requires `VIEW_PORTFOLIO`.
This merely ports the changes from #465, which currently has merge conflicts.
Fixes https://github.com/DependencyTrack/dependency-track/issues/2053
Closes #465
N/A
> Require `VIEW_PORTFOLIO` permission for BOM download

- .github/workflows/i18n.yaml
- src/views/components/PolicyViolationProgressBar.vue
- src/views/components/SeverityProgressBar.vue
Changed the font color of the progress bar to dark for for certain variants to improve readability.
Closes #814
> Enhanced ProgressBar Contrast Ration

- src/views/portfolio/projects/ProjectPolicyViolations.vue
This is exactly the same as PR #376. The commit was not signed.
Thanks @highkay
> fix missing translation

- .vscode/settings.json
For those using VSCode, this will ensure the `commit -s` flag is automatically added 
Reduce the amount of DCO check fails
> build(vscode): always sign off

- src/views/components/AboutModal.vue
Adds database name and version to the About dialog.
Closes https://github.com/DependencyTrack/dependency-track/issues/2093
N/A
> Add database name and version to About dialog

- src/views/portfolio/projects/Project.vue
If a project has many versions, the versions dropdown should be scrollable such that the user can view and select any desired version
Fixes https://github.com/DependencyTrack/frontend/issues/809
Backports #861
N/A
> Backport: Restrict Height Of Project Versions Dropdown

- package-lock.json
- src/views/policy/PolicyCondition.vue
This change allows you create a policy using the EPSS score.
#896
> add EPSS score to policies

- src/i18n/locales/fr.json
Update of french translation, mainly policy violation fields in the dashboard.
#851
> French translation update

- src/i18n/locales/de.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/i18n/locales/fr.json
- src/i18n/locales/hi.json
- src/i18n/locales/it.json
- src/i18n/locales/ja.json
- src/i18n/locales/pl.json
- src/i18n/locales/pt-BR.json
- src/i18n/locales/pt.json
- src/i18n/locales/ru.json
- src/i18n/locales/uk-UA.json
- src/i18n/locales/zh.json
- src/views/portfolio/projects/Component.vue
Ability to quickly launch a component PURL search from within a component details screen.
Allows to easily find similar projects using the same library.
Open to suggestions on a better name for this quick-launch tab.
> feat(components): quick search for projects also using component

- src/i18n/locales/fr.json
Update of french translation, mainly policy violation fields in the dashboard.
Backports #957 
N/A
> Backport: French translation update

- .github/workflows/_meta-build.yaml
Work around ghcr.io rate limiting for Trivy database downloads.
N/A
See:
* aquasecurity/trivy-action#389
* https://github.com/orgs/community/discussions/139074
> Work around ghcr.io rate limiting for Trivy database downloads

- src/views/portfolio/projects/ProjectCreateProjectModal.vue
> Fix creation of multiple projects without reloading page

- src/views/administration/accessmanagement/Teams.vue
Fixes OIDC users not being displayed in Team view.
Fixes https://github.com/DependencyTrack/frontend/issues/1033
Backports https://github.com/DependencyTrack/frontend/pull/1034
N/A
> Backport: Fix OIDC users not being displayed in Team view

- docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
Fixes NGINX ipv6 listening.
Backports https://github.com/DependencyTrack/frontend/pull/1063
N/A
> Backport: Fix NGINX ipv6 listening

- docker/Dockerfile.alpine
Bumps `nginxinc/nginx-unprivileged` base image to `1.27.2-alpine`.
Resolves a few CVEs in alpine packages.
N/A
> Bump nginxinc/nginx-unprivileged to 1.27.2-alpine

- docker/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
Follow-up for #1063 because apparently I messed up the file paths, my bad.
None
See #1063
- ~[x] This PR introduces new or alters existing behavior, and I have updated the [documentation](https://github.com/DependencyTrack/dependency-track/tree/master/docs/_docs) accordingly~
> docker: fix ipv6 listening

- src/views/portfolio/tags/TagList.vue
Fixes tags with special characters breaking the tags table.
Fixes #1081
N/A
> Fix tags with special characters breaking the tags table

- src/views/administration/configuration/WelcomeMessage.vue
No an error is showen then there is a malformed Welcome message
Fixes #1090
> Fix no error being displayed when submitting an invalid welcome message

- src/views/globalAudit/VulnerabilityAuditByOccurrence.vue
- src/views/globalAudit/VulnerabilityAuditGroupedByVulnerability.vue
- src/views/portfolio/projects/ProjectFindings.vue
- src/views/portfolio/vulnerabilities/AffectedProjects.vue
- src/views/portfolio/vulnerabilities/Vulnerability.vue
- src/views/portfolio/vulnerabilities/VulnerabilityCreateVulnerabilityModal.vue
- src/views/portfolio/vulnerabilities/VulnerabilityList.vue
Fixes missing URI encoding for vulnerability IDs.
Fixes #1097
N/A
> Fix missing URI encoding for vulnerability IDs

- docker/Dockerfile.alpine
Bumps the `nginxinc/nginx-unprivileged` base image to `1.27.3-alpine`.
Resolves a few CVEs.
N/A
> Bump nginxinc/nginx-unprivileged to 1.27.3-alpine

- src/i18n/locales/en.json
Fixed typo in  Administration => Configuration => General
> Fix typo in English translation

- package-lock.json
- package.json
Bumps dompurify from 2.4.9 to 2.5.8.
Closes #1143
Backports #998
N/A
> Backport: Bump dompurify from 2.4.9 to 2.5.8

- docker/Dockerfile.alpine
Bumps `nginx-unprivileged` base image to latest digest.
Resolves CVE-2024-11053, although it did not affect us.
N/A
> Bump `nginx-unprivileged` base image to latest digest

- src/views/administration/accessmanagement/ApiKeyListGroupItem.vue
- src/views/administration/accessmanagement/Teams.vue
Changes API key field `clearTextKey` to `key`.
Relates to https://github.com/DependencyTrack/dependency-track/issues/4652
N/A
> Change API key field `clearTextKey` to `key`

- src/views/portfolio/projects/ProjectList.vue
Fixes column visibility preference not considered for project list.
N/A
N/A
> Fix column visibility preference not considered for project list

- src/views/portfolio/projects/Project.vue
Fixes policy violation tab indicators being populated incorrectly.
Fixes #1170
N/A
> Fix policy violation tab indicators being populated incorrectly

- src/views/portfolio/projects/Project.vue
Fixes wrong policy violation tab indicator visibility conditions.
Relates to #1170
Relates to #1171
N/A
> Fix wrong policy violation tab indicator visibility conditions

- src/views/components/AboutModal.vue
Adds Bluesky link to About dialog.
Closes #1139 
N/A
> Add Bluesky link to About dialog

- src/i18n/locales/de.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/i18n/locales/fr.json
- src/i18n/locales/hi.json
- src/i18n/locales/it.json
- src/i18n/locales/ja.json
- src/i18n/locales/pl.json
- src/i18n/locales/pt-BR.json
- src/i18n/locales/pt.json
- src/i18n/locales/ru.json
- src/i18n/locales/uk-UA.json
- src/i18n/locales/zh.json
- src/views/administration/analyzers/TrivyAnalyzer.vue
Adds UI for trivy scanner package type configuration to filter detected vulnerabilities. (see backend PR)
Closes https://github.com/DependencyTrack/dependency-track/issues/4764
> Add trivy scanner option UI

- src/views/portfolio/projects/Project.vue
- src/views/portfolio/projects/ProjectDependencyGraph.vue
Fixes "show in dependency graph" yielding a 403 error.
This was a regression introduced via #658. Because the dependency graph is not rendered conditionally, depending on whether a project is a collection or not, there was now a race condition in the code that auto-selected the graph tab.
Fixes #1160
N/A
> Fix "show in dependency graph" yielding a 403 error

- docker/Dockerfile.alpine
Bumps nginx base image to latest digest.
Resolves CVE-2025-31115
N/A
> Bump nginx base image to latest digest

- src/i18n/locales/de.json
- src/i18n/locales/en.json
- src/i18n/locales/es.json
- src/i18n/locales/fr.json
- src/i18n/locales/hi.json
- src/i18n/locales/it.json
- src/i18n/locales/ja.json
- src/i18n/locales/pl.json
- src/i18n/locales/pt-BR.json
- src/i18n/locales/pt.json
- src/i18n/locales/ru.json
- src/i18n/locales/uk-UA.json
- src/i18n/locales/zh.json
- src/views/portfolio/tags/TagList.vue
- src/views/portfolio/tags/TaggedCollectionProjectListModal.vue
Show collection projects using a given tag in the tag list.
Relates to https://github.com/DependencyTrack/dependency-track/pull/4858.
> Show collection projects using tag in tag list
